### ISSUE TITLE
truffleHog: command not found

### ISSUE THREAD

**Issue by rupsray** [dxa4481/truffleHog#101]
While using **truffleHog --regex --entropy=False https://github.com/dxa4481/truffleHog.git** command getting error **truffleHog: command not found**

Is there any dependency to access the command?

**Comment by rupsray** [comment]
> python3 truffleHog.py <ssh_url of repository>
Scanned using the above command, and it solved the issue.
I have two versions of Python, default version is 2.7 and truffleHog is installed on Python 3.4. That is why I have used python3 to run the command instead of python.

**Comment by mohitk09** [comment]
Does not resolve the issue for me
