### ISSUE TITLE
Feature Request: Suppress output when run as an included module

### ISSUE THREAD

**Issue by ray-yin** [dxa4481/truffleHog#104]
The app works great when run from command line. However, it would be nice if the findings output could be suppressed when included as a module in other python projects that only need access to portions of the built in functionality or the ability to customize the output format. One possible solution is to:

1. Remove the calling of `print_results()` from `diff_worker()`
2. Add a command line argument for enabling/disabling output (on by default)
3. Add logic to `main()` for running `print_results()` when required.

Let me know if you would like me to incorporate the change into a PR.

**Comment by dxa4481** [comment]
Done
