### ISSUE TITLE
Enterprise Github API Address

### ISSUE THREAD

**Issue by zach5410** [dxa4481/truffleHog#105]
Hey,

Thanks for all of the great work that you are doing.  

I am currently trying to use TruffleHog for our business, but we have a private github server that does not point to the base api.github.com.  

Two questions:
1. Does the SearchOrg Script actually implemented?  I am seeing it, but not sure if that is the base script that all trufflehog calls go through, or if it is a WIP.

2.  Since we have a different api domain to hit, what is the best way for us to point to the correct domain?  I am thinking the SearchOrg Script, but I want to make sure.

Thanks,

~Zach

**Comment by zach5410** [comment]
I was able to find the work around.  It was a proxy issue.  So thank you for the quick response.

I did notice that after you find a secret with truffle hog.  If you remove the secret from your repo, it will still return the responses, since those were in the git commit history.  Is there anyway to bypass this?  So that it only looks at the most recent commits in a push?

**Comment by dxa4481** [comment]
That's the desired functionality, because what I've found is as many as 40% of the secrets are still live and buried in commit history. You can use BFG repo cleaner to clean up your commit history, and remove the secrets https://rtyley.github.io/bfg-repo-cleaner/
