### ISSUE TITLE
False Triggers

### ISSUE THREAD

**Issue by zach5410** [dxa4481/truffleHog#106]
Example:
1. You push up your secrets and run truffleHog
2. Truffle hog returns that secret is found
3. Make commit to remove secret and then run truffle hog
4. Truffle hog returns that secret is found

When you fix your project to not include a secret, it will still find the secret even though it has been removed.  If we are using this in a CICD capacity, this will fail the pipeline since it is still being triggered.  

What we need is the ability to look at all finished files, not the diff. Which will allow for the ability to see all current files, and not worry about all of the previous file changes.

**Comment by shoeper** [comment]
It is the purpose of the software to scan everything. And credentials in the history can be a large risk as most people wouldn't expect them there or forget what they've committed a year before and don't think about someone else could find and use them.

**Comment by zach5410** [comment]
I see, so if it is found in the history then you need to delete the commits.  

That makes sense
