### ISSUE TITLE
Just a question (not actually an issue)

### ISSUE THREAD

**Issue by ThoseGuysInTown** [dxa4481/truffleHog#12]
This repo sounds interesting but I'm not sure I fully understand it. What are some example use cases for this?

**Comment by gabinante** [comment]
Finding secrets that are committed to your git repo, even deep in the commit history. This lets you figure out if you have a potential security breach waiting in the wings.

**Comment by bandrel** [comment]
One thing to keep in mind is that it only catches secrets that have high entropy.  If the repo contains the code `password = 'password' ` it would not flag this as neither words have high entropy.  

Example 
`./truffleHog.py https://github.com/bandrel/bogus_secrets.git` 

finds `9lowltry6zt4hl8nn5o4oitadahmkdaznlkebdax9gun9wtw8igvmwkom1wp2xev` but not `cWv5M8UB2AtD8Jgf6Uhw` or any of the other examples.

**Comment by ryanohoro** [comment]
The minimum strong limit is hardcoded to 20 chars, so even high entropy passwords are unlikely to get caught up in the filter.

**Comment by bandrel** [comment]
@ryanohoro in addition to the char limit the password would need to contain only hex or base64 characters as well as these are the only two character sets hard coded into program as well.
