### ISSUE TITLE
Feature Request: Scan the Whole Org Instead of Single Project Repositories

### ISSUE THREAD

**Issue by shoaibali123** [dxa4481/truffleHog#129]
Hi, can we have a feature to scan the whole org just like other scanning tools like gitRob? Right now the target is a git project. It would be great to scan the whole org repositories regularly and follow up on results.

**Comment by dxa4481** [comment]
Hi @shoaibali123 there's a script in the scripts directory that does this. I'll try to document it a little better in the readme.

**Comment by shoaibali123** [comment]
Hi dxa4481, it doesn't work for me. I see the script in master branch but when I used it didn't work for me. Can you give more details? Thanks.
