### ISSUE TITLE
FutureWarning: Possible nested set at position 33

### ISSUE THREAD

**Issue by theHackPot** [dxa4481/truffleHog#132]
Hi,

Getting the error "FutureWarning: Possible nested set at position 33"

![error](https://user-images.githubusercontent.com/17269499/47720279-63cc7d00-dc45-11e8-9774-d00afa1320fc.JPG)

Ubuntu 16.04 LTS
Python 3.7

**Comment by dmitris** [comment]
getting the same one (RHEL7, Python 3.7):
```
/opt/python/lib/python3.7/site-packages/truffleHogRegexes/regexChecks.py:9: FutureWarning: Possible nested set at position 33
  regexes[key] = re.compile(regexes[key])
```

**Comment by snebel29** [comment]
Can this issue in fact be fixed by this? https://github.com/dxa4481/truffleHogRegexes/pull/8 assuming that the regular expression contains a typo?

or was the intention to include `[` and `]` characters to the regular expression set ?

**Comment by dxa4481** [comment]
Merged, closing this issue. Feel free to re-open if that didn't fix it.

**Comment by meetinthemiddle-be** [comment]
Getting this error as well `truffleHogRegexes/regexChecks.py:9: FutureWarning: Possible nested set at position 33`, but don't have the permissions to reopen this issue.

Environment is a hosted Ubuntu agent :
`$> python --version`
`Python 3.7.5`
`$> uname -a`
`Linux fv-az33 5.0.0-1027-azure #29~18.04.1-Ubuntu SMP Mon Nov 25 21:18:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
