### ISSUE TITLE
Cannot scan only 1 commit or lastest commit

### ISSUE THREAD

**Issue by sukritpol** [dxa4481/truffleHog#134]
I want to scan all file in the repository, for example, I check out some commit and need to scan only this commit. How can I do this thing? Could you help me please?

**Comment by dxa4481** [comment]
You should be able to use the `--max_depth=1` flag

**Comment by sukritpol** [comment]
I ever used that option but not work for me.
No result from scan, In fact, files in the repository have many credentials in files. That the reason Why I posted in the issues.

I already used 
`trufflehog --regex --entropy=False --rule=[fullpath]/regexes.json [git_url] --since_commit=[commit that i want to scan]`
and 
`trufflehog --regex --entropy=False --rule=[fullpath]/regexes.json [git_url] --max_depth=1`

I didn't get the results from 2 option. but if I used old commit I can get the result.

**Comment by dxa4481** [comment]
Can you give me the repo you're testing on? I'll try to take a look when I get some free time

**Comment by sukritpol** [comment]
I cannot give your repo because it's internal use, but I will create for test project for testing .
This is my sample repository 
https://github.com/sukritpol/test-scan-secret
if  I use option `--max_depth=1`, >> no result (I need to adjust to 2 or more)
if I use option `-since_commit=b45a26d908b541d375ffb5ae42abe293e537846c` >> no result

Question
1. I want to scan all repository in my existing repository, Can I use for that purpose?
2.  If I add to pipeline and I want to scan only commit that got from Jenkins Job, Is it possible?
