### ISSUE TITLE
 Git issue when trying to scan cloned project in Apple-mac: trufflehog file:///

### ISSUE THREAD

**Issue by dgurazada** [dxa4481/truffleHog#158]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/trufflehog", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/truffleHog/truffleHog.py", line 82, in main
    surpress_output=False, branch=args.branch, repo_path=args.repo_path, path_inclusions=path_inclusions, path_exclusions=path_exclusions)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/truffleHog/truffleHog.py", line 309, in find_strings
    project_path = clone_git_repo(git_url)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/truffleHog/truffleHog.py", line 152, in clone_git_repo
    Repo.clone_from(git_url, project_path)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/git/repo/base.py", line 925, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/git/repo/base.py", line 880, in _clone
    finalize_process(proc, stderr=stderr)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/git/util.py", line 341, in finalize_process
    proc.wait(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/git/cmd.py", line 291, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v file:///GitHub/Github-guardian/ /var/folders/37/md_m401d073bw1vt7q863pbw0000gn/T/tmpchgjs_ln
  stderr: 'Cloning into '/var/folders/37/md_m401d073bw1vt7q863pbw0000gn/T/tmpchgjs_ln'...
fatal: '/GitHub/Github-guardian/' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
'

**Comment by dxa4481** [comment]
Hi @dgurazada I think I know what the issue is.

Can you post the output of `ls -laht /GitHub/Github-guardian/` ?

**Comment by dgurazada** [comment]
![image](https://user-images.githubusercontent.com/25825955/57668714-e60f0400-75cd-11e9-99e2-83194dbf6e58.png)

**Comment by dxa4481** [comment]
Yup, looks like this isn't a git directory, otherwise we'd see a `.git` file. It is a git tool, designed to scan git repos.

Simple work around, is:

`git init && git add * && git commit -m "adding all files"`

And then the command should work.

**Comment by dgurazada** [comment]
Hi Dylan,

Sorry for the mix up. I tried with the cloned repo too having the same issue.

![image](https://user-images.githubusercontent.com/25825955/57670975-46567380-75d7-11e9-9e3e-5c505b8478b5.png)

**Comment by dxa4481** [comment]
So you're getting the same error with the cloned repo?

`fatal: '/GitHub/Github-guardian/' does not appear to be a git repository`

**Comment by dgurazada** [comment]
Almost similar

![image](https://user-images.githubusercontent.com/25825955/57671089-dac0d600-75d7-11e9-9cfa-3256ad1d32fb.png)

**Comment by dxa4481** [comment]
I believe this time around you need an extra slash in your URL `file:///` instead of `file://`

**Comment by dgurazada** [comment]
i tried that too, sorry i think i should have specified that

![image](https://user-images.githubusercontent.com/25825955/57671201-5f135900-75d8-11e9-8182-b1639b49471d.png)

**Comment by dgurazada** [comment]
After giving the full path of the folder, it is working...

Thanks for the response though

**Comment by dxa4481** [comment]
Yup no worries. Do you by chance work for this gitguardian? https://www.gitguardian.com/

I noticed a lot of the API keys offered are not in trufflehog today. Would you have any interest in open sourcing some of the regexes here? https://github.com/dxa4481/truffleHogRegexes

@dgurazada

**Comment by dgurazada** [comment]
I didn't work for the gitguardian, Dylan. I also used the name to automate the handling of github shared security controls. It's a coincidence :)

**Comment by dgurazada** [comment]
Hey Dylan, I have a case where I'm trying to scan my repo with latest code for passwords. I don't want to go back in commits and find any sensitive info. Will this be possible with trufflehog? So basically can it parse files in the repo and trigger when matches the regex? 

In my scenario i have commits with passwords but some of the passwords are updated over the commits, not all. I want to cover all the updated and the old ones that haven't changed so far.  Does it make sense?
