### ISSUE TITLE
Feature Request: Include the commit hash in the header section

### ISSUE THREAD

**Issue by gbrayut** [dxa4481/truffleHog#18]
Right now the header lists the Date, Branch, and Commit message, but this can be ambiguous and difficult to look up in the history. PR #16 adds the file name in the commit where the string was found, but it would be nice to also include the commit hash for faster lookup.

**Comment by dxa4481** [comment]
Done. This is checked into dev. Will check into master soon.

https://github.com/dxa4481/truffleHog/blob/dev/truffleHog/truffleHog.py#L108
