### ISSUE TITLE
Add usage of Docker image to docs

### ISSUE THREAD

**Issue by p3k** [dxa4481/truffleHog#211]
It’s probably straight-forward for some people using Docker more regularly than me, but it took a while to find out how to run truffleHog from Docker with my locally cloned repo:

```sh
cd /path/to/git_repo
docker run --rm -v `pwd`:/proj dxa4481/trufflehog file:///proj
```

* `-v` mounts the current working dir (`` `pwd` ``) to the `/proj` dir in the Docker container
* `file:///proj` references that very same `/proj` dir in the container (which is also set as the default working dir in the Dockerfile)

**Comment by Hydragyrum** [comment]
I like that idea, thanks for the command line :)

**Comment by ronykris** [comment]
root@kali:~/tools/truffleHog# docker run --rm -v `pwd`:/proj dxa4481/trufflehog file:///proj
standard_init_linux.go:211: exec user process caused "exec format error"
root@kali:~/tools/truffleHog#

the recommendation doesn't seem to work for me. Any recommendations?

**Comment by ronykris** [comment]
Don't know why the command snippet (above) is struckthrough. I have to admit that i am new to docker. therefore, not sure if i am messing up anywhere. Any help/assistance is appreciated.
