### ISSUE TITLE
Can't decode 0xa9, which is the copyright symbol

### ISSUE THREAD

**Issue by dullroar** [dxa4481/truffleHog#27]
This is actually more of a problem with Python's UTF8 code, I think. But if you run the trufflehog script against [this repo](https://github.com/dullroar/TW5-atomfeed), you'll get the following error:

```
Traceback (most recent call last):
  File "/home/lehmer/Sandbox/trufflehog.py", line 130, in <module>
    project_path = find_strings(args.git_url)
  File "/home/lehmer/Sandbox/trufflehog.py", line 95, in find_strings
    printableDiff = blob.diff.decode()
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa9 in position 96: invalid start byte
```

This is because an older version of the license file had a copyright symbol (0xa9, which is the rendered value of the HTML entity &copy;, for example). I figured it out by putting a `print(blob.diff)` right before line 95.

**Comment by floatingatoll** [comment]
This also trips up on other non-utf8 values (0xA0). It would be most useful if the script proceeded rather than terminating unexpectedly.

**Comment by dxa4481** [comment]
I think I fixed it. Reopen if it appears again.
