### ISSUE TITLE
ImportError: No module named git

### ISSUE THREAD

**Issue by sseering** [dxa4481/truffleHog#3]
### Full error:

> Traceback (most recent call last):
>   File "truffleHog.py", line 3, in <module>
>     from git import Repo
> ImportError: No module named git

### Steps to reproduce:

`virtualenv venv`
`. venv/bin/activate`
`pip install -r requirements.txt`
`python2 truffleHog.py git@some.domain.net:example/fox.git`

**Comment by sseering** [comment]
I found the fix: you have to tell virtualenv explicitly to use the outdated python version:

`virtualenv -p /usr/bin/python2.7 venv`

**Comment by dxa4481** [comment]
Ahh sorry about that, I'll look into python 3.x support
