### ISSUE TITLE
dangerously high memory usage potential

### ISSUE THREAD

**Issue by samdfonseca** [dxa4481/truffleHog#32]
It might be worth adding a warning to the README regarding the potential for this script to consume an extremely large amount of system memory. I ran this on an admittedly large, bloated repo (50k+ commits and a 1.2 gb `.git` directory), and it nearly took down my 2015 MBP. According to top, it was using some 60+ gb of memory, though I'm not sure how that's possible unless my laptop created a bunch of swap space automatically. Whatever the actual number was, it was at least several gb and caused me to have to force quit iterm. My fault for trying to run this on a repo that size, but a warning might help others from making the same mistake.

**Comment by dxa4481** [comment]
I've added two flags to help with this

```
  --since_commit SINCE_COMMIT
                        Only scan from a given commit hash
  --max_depth MAX_DEPTH
                        The max commit depth to go back when searching for
                        secrets
```
Feel free to reopen if you have more ideas that can help
