### ISSUE TITLE
Feature Request: Run locally only

### ISSUE THREAD

**Issue by nobe4** [dxa4481/truffleHog#33]
Howdy!

I was wondering how you would consider adding the possibility to run this to an already-cloned repo.

The feature would include making some change to the code, adding a condition to the following line: https://github.com/dxa4481/truffleHog/blob/7d8009ff0b278229a119ea6cb69025dfeed9ab49/truffleHog.py#L67 to clone the repo or not, and not remove the repo afterwards (of course).

Also this could add a new argument `local_path` for example to specify which folder to use.

If no path/argument is specified, it could be great to just scan the current folder for strings.

I'd be happy to make the change and PR it, just wanted to know if that could be of some interest before starting anything.

Any feedback?

**Comment by dxa4481** [comment]
This was taken care of with #17
