### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by nikolay** [dxa4481/truffleHog#38]
Please!

**Comment by dxa4481** [comment]
This is and has been python 3 supported. I just tested 3.5.2, can you tell me exactly which version is giving you trouble?

**Comment by bbriggs** [comment]
Just tried this with 3.6.1 on Mac and it bombed on trying to import `find_strings`

**Comment by nikolay** [comment]
@dxa4481 Any news?

**Comment by dxa4481** [comment]
I was able to reproduce the issue with the following docker file
```
from python:3.6.1-alpine
run pip install trufflehog
cmd ["trufflehog", "git@github.com:dxa4481/whatsinmyredis.git"]
```

**Comment by dxa4481** [comment]
This should work now. Reopen if there's issues.
