### ISSUE TITLE
ImportError: cannot import name 'find_strings'

### ISSUE THREAD

**Issue by ViKomprenas** [dxa4481/truffleHog#39]
```
$ truffleHog
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/bin/truffleHog", line 7, in <module>
    from truffleHog.truffleHog import main
  File "/usr/local/lib/python3.6/site-packages/truffleHog/__init__.py", line 1, in <module>
    from truffleHog import find_strings
ImportError: cannot import name 'find_strings'
$ uname -a
Darwin helium.local 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
$ python3 --version
Python 3.6.1
```

**Comment by bbriggs** [comment]
Deployed a virtualenv with Python2 and used that instead. Worked like a champ.

**Comment by alias1** [comment]
Same issue, `3.5.2`

```
⇒  trufflehog .
Traceback (most recent call last):
  File "/Users/devalias/.pyenv/versions/3.5.2/bin/trufflehog", line 7, in <module>
    from truffleHog.truffleHog import main
  File "/Users/devalias/.pyenv/versions/3.5.2/lib/python3.5/site-packages/truffleHog/__init__.py", line 1, in <module>
    from truffleHog import find_strings
ImportError: cannot import name 'find_strings'
```

**Comment by bbriggs** [comment]
@dxa4481 claims that python3 support is working, but multiple people are reporting issues with 3.5, which he says he's unable to reproduce.

Why don't we help him repro the issue so we can get it fixed? I'd like to see this fully 2/3 compatible (and on pypi!)

**Comment by alias1** [comment]
Notes:

[import find_strings](https://github.com/dxa4481/truffleHog/blob/master/truffleHog/__init__.py#L1)
```
from truffleHog import find_strings
```
[find_strings()](https://github.com/dxa4481/truffleHog/blob/master/truffleHog/truffleHog.py#L73)

Oh.. I wonder.. this could be a filename case issue.. Ran into something similar before on another project..

@ViKomprenas appears to be on OSX, and I definitely was.

Although I suppose that wouldn't really account for python 2 working probably.. *ponders*

**Comment by jingpengwu** [comment]
I get the same error with python 3.6 and anaconda3 in ubuntu 14.04

**Comment by jingpengwu** [comment]
Simply delete the error code line works
https://github.com/dxa4481/truffleHog/blob/master/truffleHog/__init__.py#L1
