### ISSUE TITLE
Feature Request: String borders for sensetive data in output

### ISSUE THREAD

**Issue by AntonKuzminRussia** [dxa4481/truffleHog#53]
Hello. Now, if i run truffleHog in cli, i see commits content and sensetive data highlighted by color. But if content is big, i move it into outfile ( > out.log). In file i can`t see colors and it hard to find sensetive strings. 
Please, add a parameter for left and right borders of sensetive strings. It help to grep it from big output content.

**Comment by dxa4481** [comment]
This is done.
