### ISSUE TITLE
password protected repos

### ISSUE THREAD

**Issue by verybigelephants** [dxa4481/truffleHog#61]
currently there is no way to pass password over to the git repostory, meaning a password protected repository will crash with this message 

```
fatal: could not read Password for '[somerepo]': Invalid argument 
```

**Comment by dxa4481** [comment]
Try either using SSH, or just clone the repo and run it locally with file:/// 

I think you can also do this, but I don't recommend it because it puts a password in your bash history
https://username:password@github.com/....

**Comment by verybigelephants** [comment]
oh thanks, i'm a noob
