### ISSUE TITLE
readme shows file:/// but doesnt seem to respect that option

### ISSUE THREAD

**Issue by carnal0wnage** [dxa4481/truffleHog#68]
readme shows file:/// but TH doesnt seem to respect that option

**Comment by milo-minderbinder** [comment]
It is working for me with the latest version of truffleHog on macOS High Sierra. May be obvious, but do note that if the URI you're passing to truffleHog's `git_url` argument starts with `file:///`, that is necessarily/by definition an absolute path URI, so you'd need to be providing the _full_ path to the file/dir you're scanning. For example:
```bash
$ echo $PWD
/Users/milo/code
$ ls
test-git-repo
$ truffleHog file://test-git-repo #THIS WILL FAIL
$ truffleHog file:///Users/milo/code/test-git-repo #THIS WORKS
$ truffleHog test-git-repo #ALSO WORKS
```
If that wasn't the issue, what version truffleHog are you using? What OS & version? What is the output you're getting when you experience this issue vs. what you were expecting?

**Comment by carnal0wnage** [comment]
it was the full path. thanks for the gentle response :-)
