### ISSUE TITLE
Needless checkout

### ISSUE THREAD

**Issue by ericfrederich** [dxa4481/truffleHog#79]
So I haven't even ran this code but was looking at the repo.
It seems there is a needless checkout of the repo [here on this line](https://github.com/dxa4481/truffleHog/blob/8c96d39ed7edf0d542c193b688985889cfd335c6/truffleHog/truffleHog.py#L198) which can be quite expensive.
I don't think there is a need to actually change the files in the working directory just to get the diffs.

I think you can just pass `rev=` [here on this line](https://github.com/dxa4481/truffleHog/blob/8c96d39ed7edf0d542c193b688985889cfd335c6/truffleHog/truffleHog.py#L203) and the code should behave the same.

You'd also get rid of that ugly `except: pass`  block.

**Comment by dxa4481** [comment]
Great tip, thank you
