### ISSUE TITLE
problem with Regex switch

### ISSUE THREAD

**Issue by outdoorguy007** [dxa4481/truffleHog#82]
Anyone else have an error message with using the regex switch?

UnboundLocalError: local variable 'regexes' referenced before assignment.  I just called 
trufflehog --regex my_code_dir/

**Comment by dxa4481** [comment]
Yeah it's a bug. I'll work on a fix this week. You can try installing an older version in the mean time.

**Comment by 0xtavian** [comment]
this also seems to be affecting custom regex changes as im unable to add custom regex. After changing or commenting out all regex it still produces the default results. thanks.

**Comment by dxa4481** [comment]
I believe this is fixed.
