### ISSUE TITLE
Feature Request: exit code if secrets found

### ISSUE THREAD

**Issue by calve** [dxa4481/truffleHog#87]
Hi !

In order to batch truffleHog, it would be great to have different exit code when truffleHog find suspicious string and when it does not.

I would suggest to return 0 when the code is clean, and 1 otherwise.

**Comment by calve** [comment]
fwiw here is my oneliner to exit whit a failure code when secrets are found:
 `trufflehog /path/to/git | ifne sh -c \"cat - && false\"`

 (`ifne` is in `moreutils` on debians)

**Comment by calve** [comment]
just opened a PR to address this

**Comment by dxa4481** [comment]
Done
