### ISSUE TITLE
Different results

### ISSUE THREAD

**Issue by relaxedricky** [dxa4481/truffleHog#90]
I've noticed calling the python program direct seems to yield different results than if I import the app into my own code and run using the following:

`truffleHog.find_strings(item["html_url"], do_regex=True, do_entropy=True)`

As an example: https://github.com/huntsman-li/go-cache throws back some entropy stuff, the python script didn't, am I missing something?

I just get the following with no other output:

```
Project Name: viewimages 
Created at: 2018-02-16T08:48:57Z                   
Updated at: 2018-02-23T04:17:28Z                   
searching https://github.com/weienlee/viewimages   

Project Name: gestalt    
Created at: 2018-02-16T22:17:51Z                   
Updated at: 2018-02-23T18:24:01Z                   
searching https://github.com/pinterest/gestalt     

Project Name: aslur      
Created at: 2018-02-16T06:29:50Z                   
Updated at: 2018-02-23T02:57:56Z                   
searching https://github.com/blackzert/aslur
```

Thanks

**Comment by dxa4481** [comment]
I believe this is because max depth was accidentally defaulted to None. I'll push a change shortly, in the mean time feel free to call find_strings with `max_depth=100000` and see if that fixes it

**Comment by relaxedricky** [comment]
I can confirm that was the issue. Thanks.
