### ISSUE TITLE
Can truffleHog use personal access tokens?

### ISSUE THREAD

**Issue by oshall** [dxa4481/truffleHog#94]
I've been attempting to use personal auth tokens but truffleHog it's failing out. Is this feature available, if so how should I call the truffleHog script?

**Comment by oshall** [comment]
Correction.....user error...just calling trufflehug the normal way works :-). The problem was, token was being passed incorrectly on my end, hence the "Authentication failed" error. 

But on another note, it seems I have to enter the token twice, because truffleHog is asking twice before the script can run. Any reason for that?

`pip show trufflehog
Name: truffleHog
Version: 2.0.88
Summary: Searches through git repositories for high entropy strings, digging deep into commit history.
Home-page: https://github.com/dxa4481/truffleHog
Author: Dylan Ayrey
Author-email: dxa4481@rit.edu
License: GNU
Location: /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Requires: GitPython`

**Comment by dxa4481** [comment]
Not really sure why it would ask for the token twice. I use SSH auth, you can try switching to that.
