### ISSUE TITLE
Readme mentions legacy trufflehog/regexChecks.py

### ISSUE THREAD

**Issue by elliottb303** [dxa4481/truffleHog#99]
readme looks incorrect and doesn't refer to external repo containing regex json

**Comment by dxa4481** [comment]
Yup I did a recent change which put the regexes in an external json file. You can include custom ones with a configuration flag, I will update the documentation soon.

**Comment by elliottb303** [comment]
Yeah I created a virtual env to get around some git module ssl issues, and of course Pycharm virtual env was not linking correctly and showed missing regexes dependency. Went in a little circle but found the regex file eventually.

Great module!

On a separate regex troubleshooting note, I am seeing different results in truffleHog vs generic re.match. Any idea why a beginning of line '^' would not match strings correctly in the module? Looks to working in an editor like pythex.org, and even in python console, however not getting the correct match in truffleHog? If I remove the beginning of line token it matches, 

    "Possible hardcoded passwords": "^.{1,20}PASSWORD.{1,20}[ =]?.*" # not working
    "Possible hardcoded passwords": ".{1,20}PASSWORD.{1,20}[ =]?.*" . # works, but against arbitrary long lines like -> " source code form), and must require no special password or key for" 


This seems to fail for even simple match like "^user.*"

I know looking for the word password seems limited, but going or it.

Thanks again!

**Comment by elliottb303** [comment]
I just realized the diff being compared is a string, and likely not ran through line by line

**Comment by dxa4481** [comment]
Updated the readme
